name: Linter

on:
  push:
    # Only run if,
    paths:
      # Changes in python files
      - "**.py"
    branches:
      - master
  pull_request:
    # Only run if,
    paths:
      # Changes in python
      - "**.py"
    branches:
      - master

jobs:
   lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install pipenv
        uses: dschep/install-pipenv-action@v1
      - name: Install dependencies
        run: |
          pipenv install --dev
      - name: Testing with flake8
        run: |
          mkdir test-reports
          pipenv run flake8 ./ --output-file test-reports/flake8
      - name: Testing with black
        run: |
          pipenv run black --check ./
      - name: Upload flake test results
        uses: actions/upload-artifact@master
        with:
          name: flake-report
          path: test-reports/flake8
        # Use failure() to upload only if failure occurs
        if: failure()
